//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.2
//  Machine:  TX-P-0038
//  DateTime: 2/15/2018 2:34:17 PM
//  UserName: artem.glynskyi
//  GPLEX input file <Runner.Language.analyzer.lex - 2/15/2018 2:34:16 PM>
//  GPLEX frame file <embedded resource>
//
//  Option settings: verbose, parser, stack, minimize
//  Option settings: compressNext, persistBuffer, noEmbedBuffers
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define STACK
#define PERSIST
#define BYTEMODE

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using QUT.GplexBuffers;

namespace AvgJavascriptVm.Complier
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     internal enum Token
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     internal abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     internal interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     internal sealed partial class RunnerScanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     internal sealed partial class RunnerScanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Token).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 91;
        const int initial = 92;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int STRING = 1;

#region user code
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public sbyte[] nxt;
        public Table(int m, int x, int d, sbyte[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {92, 85, 0};

    static Table[] NxS = new Table[106] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ // Shortest string "\t"
      new Table(9, 24, -1, new sbyte[] {1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 1}),
/* NxS[   2] */ new Table(0, 0, -1, null), // Shortest string "\""
/* NxS[   3] */ // Shortest string "%"
      new Table(61, 1, -1, new sbyte[] {82}),
/* NxS[   4] */ new Table(0, 0, -1, null), // Shortest string "("
/* NxS[   5] */ new Table(0, 0, -1, null), // Shortest string ")"
/* NxS[   6] */ // Shortest string "*"
      new Table(42, 20, -1, new sbyte[] {78, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 79}),
/* NxS[   7] */ // Shortest string "+"
      new Table(43, 19, -1, new sbyte[] {76, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 77}),
/* NxS[   8] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[   9] */ // Shortest string "-"
      new Table(45, 17, -1, new sbyte[] {74, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 75}),
/* NxS[  10] */ new Table(0, 0, -1, null), // Shortest string "."
/* NxS[  11] */ // Shortest string "/"
      new Table(61, 1, -1, new sbyte[] {73}),
/* NxS[  12] */ // Shortest string "0"
      new Table(46, 12, -1, new sbyte[] {100, -1, 12, 12, 12, 12, 
          12, 12, 12, 12, 12, 12}),
/* NxS[  13] */ new Table(0, 0, -1, null), // Shortest string ":"
/* NxS[  14] */ new Table(0, 0, -1, null), // Shortest string ";"
/* NxS[  15] */ // Shortest string "<"
      new Table(60, 2, -1, new sbyte[] {99, 70}),
/* NxS[  16] */ // Shortest string "="
      new Table(61, 1, -1, new sbyte[] {68}),
/* NxS[  17] */ // Shortest string ">"
      new Table(61, 2, -1, new sbyte[] {65, 97}),
/* NxS[  18] */ // Shortest string "A"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  19] */ new Table(0, 0, -1, null), // Shortest string "["
/* NxS[  20] */ new Table(0, 0, -1, null), // Shortest string "]"
/* NxS[  21] */ // Shortest string "d"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 63, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  22] */ // Shortest string "e"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 60, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  23] */ // Shortest string "f"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 47, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 48, 18, 18, 18, 18, 18, 49, 
          18, 18, 18, 18, 18}),
/* NxS[  24] */ // Shortest string "i"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          46, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  25] */ // Shortest string "r"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 41, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  26] */ // Shortest string "t"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 38, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  27] */ // Shortest string "v"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 36, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  28] */ // Shortest string "w"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 32, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  29] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  30] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  31] */ new Table(0, 0, -1, null), // Shortest string "|="
/* NxS[  32] */ // Shortest string "wh"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 33, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  33] */ // Shortest string "whi"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 34, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  34] */ // Shortest string "whil"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 35, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  35] */ // Shortest string "while"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  36] */ // Shortest string "va"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 37, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  37] */ // Shortest string "var"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  38] */ // Shortest string "tr"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 39, 
          18, 18, 18, 18, 18}),
/* NxS[  39] */ // Shortest string "tru"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 40, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  40] */ // Shortest string "true"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  41] */ // Shortest string "re"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 42, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  42] */ // Shortest string "ret"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 43, 
          18, 18, 18, 18, 18}),
/* NxS[  43] */ // Shortest string "retu"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 44, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  44] */ // Shortest string "retur"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 45, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  45] */ // Shortest string "return"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  46] */ // Shortest string "if"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  47] */ // Shortest string "fa"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 57, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  48] */ // Shortest string "fo"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 56, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  49] */ // Shortest string "fu"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 50, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  50] */ // Shortest string "fun"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 51, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  51] */ // Shortest string "func"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 52, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  52] */ // Shortest string "funct"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 53, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  53] */ // Shortest string "functi"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 54, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  54] */ // Shortest string "functio"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 55, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  55] */ // Shortest string "function"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  56] */ // Shortest string "for"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  57] */ // Shortest string "fal"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 58, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  58] */ // Shortest string "fals"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 59, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  59] */ // Shortest string "false"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  60] */ // Shortest string "el"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 61, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  61] */ // Shortest string "els"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 62, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  62] */ // Shortest string "else"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  63] */ // Shortest string "do"
      new Table(48, 75, -1, new sbyte[] {18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, -1, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, -1, -1, -1, -1, -1, -1, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18}),
/* NxS[  64] */ new Table(0, 0, -1, null), // Shortest string "^="
/* NxS[  65] */ new Table(0, 0, -1, null), // Shortest string ">="
/* NxS[  66] */ new Table(0, 0, -1, null), // Shortest string ">>="
/* NxS[  67] */ new Table(0, 0, -1, null), // Shortest string ">>>="
/* NxS[  68] */ // Shortest string "=="
      new Table(61, 1, -1, new sbyte[] {69}),
/* NxS[  69] */ new Table(0, 0, -1, null), // Shortest string "==="
/* NxS[  70] */ new Table(0, 0, -1, null), // Shortest string "<="
/* NxS[  71] */ new Table(0, 0, -1, null), // Shortest string "<<="
/* NxS[  72] */ // Shortest string "0.0"
      new Table(48, 10, -1, new sbyte[] {72, 72, 72, 72, 72, 72, 
          72, 72, 72, 72}),
/* NxS[  73] */ new Table(0, 0, -1, null), // Shortest string "/="
/* NxS[  74] */ new Table(0, 0, -1, null), // Shortest string "--"
/* NxS[  75] */ new Table(0, 0, -1, null), // Shortest string "-="
/* NxS[  76] */ new Table(0, 0, -1, null), // Shortest string "++"
/* NxS[  77] */ new Table(0, 0, -1, null), // Shortest string "+="
/* NxS[  78] */ // Shortest string "**"
      new Table(61, 1, -1, new sbyte[] {80}),
/* NxS[  79] */ new Table(0, 0, -1, null), // Shortest string "*="
/* NxS[  80] */ new Table(0, 0, -1, null), // Shortest string "**="
/* NxS[  81] */ new Table(0, 0, -1, null), // Shortest string "&="
/* NxS[  82] */ new Table(0, 0, -1, null), // Shortest string "%="
/* NxS[  83] */ // Shortest string "!="
      new Table(61, 1, -1, new sbyte[] {84}),
/* NxS[  84] */ new Table(0, 0, -1, null), // Shortest string "!=="
/* NxS[  85] */ // Shortest string ""
      new Table(10, 115, 86, new sbyte[] {87, 88, 86, 87, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 
          86, 86, 89, 86, 86, 86, 86, 89, -1, -1, 86, 86, 86, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, -1, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 101, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 87}),
/* NxS[  86] */ // Shortest string "\x01"
      new Table(10, 115, 86, new sbyte[] {-1, 86, 86, -1, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 
          86, 86, -1, 86, 86, 86, 86, -1, -1, -1, 86, 86, 86, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, -1, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, -1, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, -1}),
/* NxS[  87] */ new Table(0, 0, -1, null), // Shortest string "\n"
/* NxS[  88] */ // Shortest string "\x0B"
      new Table(10, 115, 86, new sbyte[] {-1, 86, 86, -1, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 
          86, 86, -1, 86, 86, 86, 86, -1, -1, -1, 86, 86, 86, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, -1, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, -1, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, -1}),
/* NxS[  89] */ new Table(0, 0, -1, null), // Shortest string "\""
/* NxS[  90] */ new Table(0, 0, -1, null), // Shortest string "\\\""
/* NxS[  91] */ new Table(0, 0, -1, null), // Shortest string "\\u0000"
/* NxS[  92] */ // Shortest string ""
      new Table(9, 117, -1, new sbyte[] {1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 1, 93, 2, -1, -1, 3, 94, 2, 4, 5, 6, 7, 8, 9, 10, 
          11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 14, 15, 16, 17, 
          -1, -1, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
          18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, -1, 20, 95, 
          -1, -1, 18, 18, 18, 21, 22, 23, 18, 18, 24, 18, 18, 18, 18, 18, 
          18, 18, 18, 25, 18, 26, 18, 27, 28, 18, 18, 18, 29, 96, 30}),
/* NxS[  93] */ // Shortest string "!"
      new Table(61, 1, -1, new sbyte[] {83}),
/* NxS[  94] */ // Shortest string "&"
      new Table(61, 1, -1, new sbyte[] {81}),
/* NxS[  95] */ // Shortest string "^"
      new Table(61, 1, -1, new sbyte[] {64}),
/* NxS[  96] */ // Shortest string "|"
      new Table(61, 1, -1, new sbyte[] {31}),
/* NxS[  97] */ // Shortest string ">>"
      new Table(61, 2, -1, new sbyte[] {66, 98}),
/* NxS[  98] */ // Shortest string ">>>"
      new Table(61, 1, -1, new sbyte[] {67}),
/* NxS[  99] */ // Shortest string "<<"
      new Table(61, 1, -1, new sbyte[] {71}),
/* NxS[ 100] */ // Shortest string "0."
      new Table(48, 10, -1, new sbyte[] {72, 72, 72, 72, 72, 72, 
          72, 72, 72, 72}),
/* NxS[ 101] */ // Shortest string "\\"
      new Table(34, 91, -1, new sbyte[] {90, -1, -1, -1, -1, 90, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 90, -1, -1, -1, -1, -1, 90, -1, -1, -1, 90, -1, 
          -1, -1, -1, -1, -1, -1, 90, -1, -1, -1, 90, -1, 90, 102, 90, -1, 
          -1, -1, -1, -1, 90}),
/* NxS[ 102] */ // Shortest string "\\u"
      new Table(48, 55, -1, new sbyte[] {103, 103, 103, 103, 103, 103, 
          103, 103, 103, 103, -1, -1, -1, -1, -1, -1, -1, 103, 103, 103, 103, 103, 
          103, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 103, 103, 103, 103, 103, 
          103}),
/* NxS[ 103] */ // Shortest string "\\u0"
      new Table(48, 55, -1, new sbyte[] {104, 104, 104, 104, 104, 104, 
          104, 104, 104, 104, -1, -1, -1, -1, -1, -1, -1, 104, 104, 104, 104, 104, 
          104, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 104, 104, 104, 104, 104, 
          104}),
/* NxS[ 104] */ // Shortest string "\\u00"
      new Table(48, 55, -1, new sbyte[] {105, 105, 105, 105, 105, 105, 
          105, 105, 105, 105, -1, -1, -1, -1, -1, -1, -1, 105, 105, 105, 105, 105, 
          105, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 105, 105, 105, 105, 105, 
          105}),
/* NxS[ 105] */ // Shortest string "\\u000"
      new Table(48, 55, -1, new sbyte[] {91, 91, 91, 91, 91, 91, 
          91, 91, 91, 91, -1, -1, -1, -1, -1, -1, -1, 91, 91, 91, 91, 91, 
          91, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 91, 91, 91, 91, 91, 
          91}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = (byte)(code - NxS[state].min);
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     internal RunnerScanner(Stream file) {
            SetSource(file); // no unicode option
        }   
#endif // !NOFILES

     internal RunnerScanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Token next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Token)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
            try {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Token.EOF;
            break;
        case 1: // Recognized '{Space}+',	Shortest string "\t"
/* skip */

/* Begin string */
            break;
        case 2: // Recognized '(\"|\')',	Shortest string "\""
BeginString();
            break;
        case 3: // Recognized '"%"',	Shortest string "%"
return (int)Token.REMAINDER;
            break;
        case 4: // Recognized '"("',	Shortest string "("
return (int)Token.LPARENTH;
            break;
        case 5: // Recognized '")"',	Shortest string ")"
return (int)Token.RPARENTH;
            break;
        case 6: // Recognized '"*"',	Shortest string "*"
return (int)Token.MULTIPLICATION;
            break;
        case 7: // Recognized '"+"',	Shortest string "+"
return (int)Token.ADDITION;
            break;
        case 8: // Recognized '","',	Shortest string ","
return (int)Token.COMMA;
            break;
        case 9: // Recognized '"-"',	Shortest string "-"
return (int)Token.SUBTRACTION;
            break;
        case 10: // Recognized '"."',	Shortest string "."
return (int)Token.DOT;
            break;
        case 11: // Recognized '"/"',	Shortest string "/"
return (int)Token.DIVISION;
            break;
        case 12: // Recognized '{Number}',	Shortest string "0"
        case 72: // Recognized '{Number}',	Shortest string "0.0"
GetNumber(); return (int)Token.NUMBER;
            break;
        case 13: // Recognized '":"',	Shortest string ":"
return (int)Token.COLON;
            break;
        case 14: // Recognized '";"',	Shortest string ";"
return (int)Token.SEMICOLON;
            break;
        case 15: // Recognized '"<"',	Shortest string "<"
return (int)Token.LESSTHAN;
            break;
        case 16: // Recognized '"="',	Shortest string "="
return (int)Token.ASSIGN;
            break;
        case 17: // Recognized '">"',	Shortest string ">"
return (int)Token.GREATERTHAN;
            break;
        case 18: // Recognized '{Identifier}',	Shortest string "A"
        case 21: // Recognized '{Identifier}',	Shortest string "d"
        case 22: // Recognized '{Identifier}',	Shortest string "e"
        case 23: // Recognized '{Identifier}',	Shortest string "f"
        case 24: // Recognized '{Identifier}',	Shortest string "i"
        case 25: // Recognized '{Identifier}',	Shortest string "r"
        case 26: // Recognized '{Identifier}',	Shortest string "t"
        case 27: // Recognized '{Identifier}',	Shortest string "v"
        case 28: // Recognized '{Identifier}',	Shortest string "w"
        case 32: // Recognized '{Identifier}',	Shortest string "wh"
        case 33: // Recognized '{Identifier}',	Shortest string "whi"
        case 34: // Recognized '{Identifier}',	Shortest string "whil"
        case 36: // Recognized '{Identifier}',	Shortest string "va"
        case 38: // Recognized '{Identifier}',	Shortest string "tr"
        case 39: // Recognized '{Identifier}',	Shortest string "tru"
        case 41: // Recognized '{Identifier}',	Shortest string "re"
        case 42: // Recognized '{Identifier}',	Shortest string "ret"
        case 43: // Recognized '{Identifier}',	Shortest string "retu"
        case 44: // Recognized '{Identifier}',	Shortest string "retur"
        case 47: // Recognized '{Identifier}',	Shortest string "fa"
        case 48: // Recognized '{Identifier}',	Shortest string "fo"
        case 49: // Recognized '{Identifier}',	Shortest string "fu"
        case 50: // Recognized '{Identifier}',	Shortest string "fun"
        case 51: // Recognized '{Identifier}',	Shortest string "func"
        case 52: // Recognized '{Identifier}',	Shortest string "funct"
        case 53: // Recognized '{Identifier}',	Shortest string "functi"
        case 54: // Recognized '{Identifier}',	Shortest string "functio"
        case 57: // Recognized '{Identifier}',	Shortest string "fal"
        case 58: // Recognized '{Identifier}',	Shortest string "fals"
        case 60: // Recognized '{Identifier}',	Shortest string "el"
        case 61: // Recognized '{Identifier}',	Shortest string "els"
GetIdentifier(); return (int)Token.IDENTIFIER;
            break;
        case 19: // Recognized '"["',	Shortest string "["
return (int)Token.LBRACKET;
            break;
        case 20: // Recognized '"]"',	Shortest string "]"
return (int)Token.RBRACKET;
            break;
        case 29: // Recognized '"{"',	Shortest string "{"
return (int)Token.LCURLYBRACE;
            break;
        case 30: // Recognized '"}"',	Shortest string "}"
return (int)Token.RCURLYBRACE;
            break;
        case 31: // Recognized '"|="',	Shortest string "|="
return (int)Token.BITWISEORASSG;
            break;
        case 35: // Recognized '"while"',	Shortest string "while"
return (int)Token.WHILE;
            break;
        case 37: // Recognized '"var"',	Shortest string "var"
return (int)Token.VAR;
            break;
        case 40: // Recognized '"true"',	Shortest string "true"
return (int)Token.TRUE;
            break;
        case 45: // Recognized '"return"',	Shortest string "return"
return (int)Token.RETURN;
            break;
        case 46: // Recognized '"if"',	Shortest string "if"
return (int)Token.IF;
            break;
        case 55: // Recognized '"function"',	Shortest string "function"
return (int)Token.FUNCTION;
            break;
        case 56: // Recognized '"for"',	Shortest string "for"
return (int)Token.FOR;
            break;
        case 59: // Recognized '"false"',	Shortest string "false"
return (int)Token.TRUE;
            break;
        case 62: // Recognized '"else"',	Shortest string "else"
return (int)Token.ELSE;
            break;
        case 63: // Recognized '"do"',	Shortest string "do"
return (int)Token.DO;
            break;
        case 64: // Recognized '"^="',	Shortest string "^="
return (int)Token.BITWISEXORASSG;
            break;
        case 65: // Recognized '">="',	Shortest string ">="
return (int)Token.GREATERTHANOREQUAL;
            break;
        case 66: // Recognized '">>="',	Shortest string ">>="
return (int)Token.RIGHTSHFTASSG;
            break;
        case 67: // Recognized '">>>="',	Shortest string ">>>="
return (int)Token.URIGHTSHFTASSG;
            break;
        case 68: // Recognized '"=="',	Shortest string "=="
return (int)Token.EQUAL;
            break;
        case 69: // Recognized '"==="',	Shortest string "==="
return (int)Token.STRICTEQUAL;
            break;
        case 70: // Recognized '"<="',	Shortest string "<="
return (int)Token.LESSTHANOREQUAL;
            break;
        case 71: // Recognized '"<<="',	Shortest string "<<="
return (int)Token.LEFTSHFTASSG;
            break;
        case 73: // Recognized '"/="',	Shortest string "/="
return (int)Token.DIVASSG;
            break;
        case 74: // Recognized '"--"',	Shortest string "--"
return (int)Token.DECREMENT;
            break;
        case 75: // Recognized '"-="',	Shortest string "-="
return (int)Token.SUBASSG;
            break;
        case 76: // Recognized '"++"',	Shortest string "++"
return (int)Token.INCREMENT;
            break;
        case 77: // Recognized '"+="',	Shortest string "+="
return (int)Token.ADDASSG;
            break;
        case 78: // Recognized '"**"',	Shortest string "**"
return (int)Token.EXPONENTIATION;
            break;
        case 79: // Recognized '"*="',	Shortest string "*="
return (int)Token.MULTASSG;
            break;
        case 80: // Recognized '"**="',	Shortest string "**="
return (int)Token.EXPASSG;
            break;
        case 81: // Recognized '"&="',	Shortest string "&="
return (int)Token.BITWISEANDASSG;
            break;
        case 82: // Recognized '"%="',	Shortest string "%="
return (int)Token.REMASSG;
            break;
        case 83: // Recognized '"!="',	Shortest string "!="
return (int)Token.NOTEQUAL;
            break;
        case 84: // Recognized '"!=="',	Shortest string "!=="
return (int)Token.STRICTNOTEQUAL;
            break;
        case 85: // In <STRING> Recognized '[^(\r\n?|\n)|\"|\'|\\]*',	Shortest string ""
        case 86: // In <STRING> Recognized '[^(\r\n?|\n)|\"|\'|\\]*',	Shortest string "\x01"
AppendString();
            break;
        case 87: // In <STRING> Recognized '[\r|\n|\v]',	Shortest string "\n"
        case 88: // In <STRING> Recognized '[\r|\n|\v]',	Shortest string "\x0B"
throw new ApplicationException("Inside string cannot contains end of line");
            break;
        case 89: // In <STRING> Recognized '(\"|\')',	Shortest string "\""
if(AppendString()) return (int)Token.STRING;
            break;
        case 90: // In <STRING> Recognized '\\[b|t|n|v|f|f|r|\"|\'|\\]',	Shortest string "\\\""
AppendStringEscapedSymbol();
            break;
        case 91: // In <STRING> Recognized '\\u([0-9a-fA-F]){4}',	Shortest string "\\u0000"
AppendStringUnicodeSymbol();
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
            } // end try
            finally {
// User-specified epilog to scan()
yylloc = new QUT.Gppg.LexLocation(tokLin, tokCol, tokELin, tokECol);
// End, user-specified epilog
            } // end finally
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
    } // end class $Scanner


} // end namespace
